spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URI}
    username: ${DATABASE_USERNAME}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
